export const weatherreports = [
    {
        "location": {
            "name": "London",
            "region": "City of London, Greater London",
            "country": "United Kingdom",
            "lat": 51.52,
            "lon": -0.11,
            "tz_id": "Europe/London",
            "localtime_epoch": 1638867910,
            "localtime": "2021-12-07 9:05"
        },
        "current": {
            "last_updated_epoch": 1638864000,
            "last_updated": "2021-12-07 08:00",
            "temp_c": 4.0,
            "temp_f": 39.2,
            "is_day": 1,
            "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
            },
            "wind_mph": 9.4,
            "wind_kph": 15.1,
            "wind_degree": 130,
            "wind_dir": "SE",
            "pressure_mb": 1004.0,
            "pressure_in": 29.65,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 81,
            "cloud": 0,
            "feelslike_c": 1.4,
            "feelslike_f": 34.5,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "uv": 1.0,
            "gust_mph": 12.8,
            "gust_kph": 20.5
        },
        "forecast": {
            "forecastday": [
                {
                    "date": "2021-12-07",
                    "date_epoch": 1638835200,
                    "day": {
                        "maxtemp_c": 8.7,
                        "maxtemp_f": 47.7,
                        "mintemp_c": 2.4,
                        "mintemp_f": 36.3,
                        "avgtemp_c": 5.5,
                        "avgtemp_f": 42.0,
                        "maxwind_mph": 24.8,
                        "maxwind_kph": 40.0,
                        "totalprecip_mm": 6.2,
                        "totalprecip_in": 0.24,
                        "avgvis_km": 9.5,
                        "avgvis_miles": 5.0,
                        "avghumidity": 78.0,
                        "daily_will_it_rain": 1,
                        "daily_chance_of_rain": 96,
                        "daily_will_it_snow": 0,
                        "daily_chance_of_snow": 0,
                        "condition": {
                            "text": "Moderate rain",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/302.png",
                            "code": 1189
                        },
                        "uv": 1.0
                    },
                    "astro": {
                        "sunrise": "07:52 AM",
                        "sunset": "03:52 PM",
                        "moonrise": "11:28 AM",
                        "moonset": "07:10 PM",
                        "moon_phase": "First Quarter",
                        "moon_illumination": "28"
                    },
                    "hour": [
                        {
                            "time_epoch": 1638835200,
                            "time": "2021-12-07 00:00",
                            "temp_c": 4.2,
                            "temp_f": 39.6,
                            "is_day": 0,
                            "condition": {
                                "text": "Clear",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                                "code": 1000
                            },
                            "wind_mph": 9.4,
                            "wind_kph": 15.1,
                            "wind_degree": 269,
                            "wind_dir": "W",
                            "pressure_mb": 1009.0,
                            "pressure_in": 29.81,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 76,
                            "cloud": 4,
                            "feelslike_c": 0.7,
                            "feelslike_f": 33.3,
                            "windchill_c": 0.7,
                            "windchill_f": 33.3,
                            "heatindex_c": 4.2,
                            "heatindex_f": 39.6,
                            "dewpoint_c": 0.4,
                            "dewpoint_f": 32.7,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 15.0,
                            "gust_kph": 24.1,
                            "uv": 1.0
                        },
                        {
                            "time_epoch": 1638838800,
                            "time": "2021-12-07 01:00",
                            "temp_c": 4.0,
                            "temp_f": 39.2,
                            "is_day": 0,
                            "condition": {
                                "text": "Clear",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                                "code": 1000
                            },
                            "wind_mph": 8.7,
                            "wind_kph": 14.0,
                            "wind_degree": 265,
                            "wind_dir": "W",
                            "pressure_mb": 1010.0,
                            "pressure_in": 29.81,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 76,
                            "cloud": 3,
                            "feelslike_c": 0.7,
                            "feelslike_f": 33.3,
                            "windchill_c": 0.7,
                            "windchill_f": 33.3,
                            "heatindex_c": 4.0,
                            "heatindex_f": 39.2,
                            "dewpoint_c": 0.2,
                            "dewpoint_f": 32.4,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 13.9,
                            "gust_kph": 22.3,
                            "uv": 1.0
                        },
                        {
                            "time_epoch": 1638842400,
                            "time": "2021-12-07 02:00",
                            "temp_c": 3.7,
                            "temp_f": 38.7,
                            "is_day": 0,
                            "condition": {
                                "text": "Clear",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                                "code": 1000
                            },
                            "wind_mph": 7.4,
                            "wind_kph": 11.9,
                            "wind_degree": 260,
                            "wind_dir": "W",
                            "pressure_mb": 1010.0,
                            "pressure_in": 29.82,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 78,
                            "cloud": 15,
                            "feelslike_c": 0.7,
                            "feelslike_f": 33.3,
                            "windchill_c": 0.7,
                            "windchill_f": 33.3,
                            "heatindex_c": 3.7,
                            "heatindex_f": 38.7,
                            "dewpoint_c": 0.2,
                            "dewpoint_f": 32.4,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 11.9,
                            "gust_kph": 19.1,
                            "uv": 1.0
                        },
                        {
                            "time_epoch": 1638846000,
                            "time": "2021-12-07 03:00",
                            "temp_c": 3.2,
                            "temp_f": 37.8,
                            "is_day": 0,
                            "condition": {
                                "text": "Overcast",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
                                "code": 1009
                            },
                            "wind_mph": 6.5,
                            "wind_kph": 10.4,
                            "wind_degree": 245,
                            "wind_dir": "WSW",
                            "pressure_mb": 1010.0,
                            "pressure_in": 29.81,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 81,
                            "cloud": 92,
                            "feelslike_c": 0.4,
                            "feelslike_f": 32.7,
                            "windchill_c": 0.4,
                            "windchill_f": 32.7,
                            "heatindex_c": 3.2,
                            "heatindex_f": 37.8,
                            "dewpoint_c": 0.2,
                            "dewpoint_f": 32.4,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 10.7,
                            "gust_kph": 17.3,
                            "uv": 1.0
                        },
                        {
                            "time_epoch": 1638849600,
                            "time": "2021-12-07 04:00",
                            "temp_c": 2.9,
                            "temp_f": 37.2,
                            "is_day": 0,
                            "condition": {
                                "text": "Clear",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                                "code": 1000
                            },
                            "wind_mph": 5.4,
                            "wind_kph": 8.6,
                            "wind_degree": 221,
                            "wind_dir": "SW",
                            "pressure_mb": 1009.0,
                            "pressure_in": 29.8,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 83,
                            "cloud": 12,
                            "feelslike_c": 0.5,
                            "feelslike_f": 32.9,
                            "windchill_c": 0.5,
                            "windchill_f": 32.9,
                            "heatindex_c": 2.9,
                            "heatindex_f": 37.2,
                            "dewpoint_c": 0.2,
                            "dewpoint_f": 32.4,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 9.2,
                            "gust_kph": 14.8,
                            "uv": 1.0
                        },
                        {
                            "time_epoch": 1638853200,
                            "time": "2021-12-07 05:00",
                            "temp_c": 2.6,
                            "temp_f": 36.7,
                            "is_day": 0,
                            "condition": {
                                "text": "Clear",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                                "code": 1000
                            },
                            "wind_mph": 4.7,
                            "wind_kph": 7.6,
                            "wind_degree": 193,
                            "wind_dir": "SSW",
                            "pressure_mb": 1008.0,
                            "pressure_in": 29.77,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 84,
                            "cloud": 8,
                            "feelslike_c": 0.4,
                            "feelslike_f": 32.7,
                            "windchill_c": 0.4,
                            "windchill_f": 32.7,
                            "heatindex_c": 2.6,
                            "heatindex_f": 36.7,
                            "dewpoint_c": 0.1,
                            "dewpoint_f": 32.2,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 8.3,
                            "gust_kph": 13.3,
                            "uv": 1.0
                        },
                        {
                            "time_epoch": 1638856800,
                            "time": "2021-12-07 06:00",
                            "temp_c": 2.4,
                            "temp_f": 36.3,
                            "is_day": 0,
                            "condition": {
                                "text": "Partly cloudy",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                                "code": 1003
                            },
                            "wind_mph": 4.5,
                            "wind_kph": 7.2,
                            "wind_degree": 178,
                            "wind_dir": "S",
                            "pressure_mb": 1008.0,
                            "pressure_in": 29.75,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 83,
                            "cloud": 29,
                            "feelslike_c": 0.3,
                            "feelslike_f": 32.5,
                            "windchill_c": 0.3,
                            "windchill_f": 32.5,
                            "heatindex_c": 2.4,
                            "heatindex_f": 36.3,
                            "dewpoint_c": -0.2,
                            "dewpoint_f": 31.6,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 8.3,
                            "gust_kph": 13.3,
                            "uv": 1.0
                        },
                        {
                            "time_epoch": 1638860400,
                            "time": "2021-12-07 07:00",
                            "temp_c": 2.4,
                            "temp_f": 36.3,
                            "is_day": 0,
                            "condition": {
                                "text": "Overcast",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
                                "code": 1009
                            },
                            "wind_mph": 4.7,
                            "wind_kph": 7.6,
                            "wind_degree": 154,
                            "wind_dir": "SSE",
                            "pressure_mb": 1007.0,
                            "pressure_in": 29.73,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 81,
                            "cloud": 96,
                            "feelslike_c": 0.2,
                            "feelslike_f": 32.4,
                            "windchill_c": 0.2,
                            "windchill_f": 32.4,
                            "heatindex_c": 2.4,
                            "heatindex_f": 36.3,
                            "dewpoint_c": -0.6,
                            "dewpoint_f": 30.9,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 9.2,
                            "gust_kph": 14.8,
                            "uv": 1.0
                        },
                        {
                            "time_epoch": 1638864000,
                            "time": "2021-12-07 08:00",
                            "temp_c": 2.8,
                            "temp_f": 37.0,
                            "is_day": 1,
                            "condition": {
                                "text": "Cloudy",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/119.png",
                                "code": 1006
                            },
                            "wind_mph": 6.5,
                            "wind_kph": 10.4,
                            "wind_degree": 133,
                            "wind_dir": "SE",
                            "pressure_mb": 1005.0,
                            "pressure_in": 29.67,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 79,
                            "cloud": 81,
                            "feelslike_c": -0.1,
                            "feelslike_f": 31.8,
                            "windchill_c": -0.1,
                            "windchill_f": 31.8,
                            "heatindex_c": 2.8,
                            "heatindex_f": 37.0,
                            "dewpoint_c": -0.5,
                            "dewpoint_f": 31.1,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 12.8,
                            "gust_kph": 20.5,
                            "uv": 1.0
                        },
                        {
                            "time_epoch": 1638867600,
                            "time": "2021-12-07 09:00",
                            "temp_c": 4.1,
                            "temp_f": 39.4,
                            "is_day": 1,
                            "condition": {
                                "text": "Overcast",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
                                "code": 1009
                            },
                            "wind_mph": 9.8,
                            "wind_kph": 15.8,
                            "wind_degree": 137,
                            "wind_dir": "SE",
                            "pressure_mb": 1003.0,
                            "pressure_in": 29.63,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 77,
                            "cloud": 100,
                            "feelslike_c": 0.5,
                            "feelslike_f": 32.9,
                            "windchill_c": 0.5,
                            "windchill_f": 32.9,
                            "heatindex_c": 4.1,
                            "heatindex_f": 39.4,
                            "dewpoint_c": 0.4,
                            "dewpoint_f": 32.7,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 17.7,
                            "gust_kph": 28.4,
                            "uv": 1.0
                        },
                        {
                            "time_epoch": 1638871200,
                            "time": "2021-12-07 10:00",
                            "temp_c": 5.8,
                            "temp_f": 42.4,
                            "is_day": 1,
                            "condition": {
                                "text": "Overcast",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
                                "code": 1009
                            },
                            "wind_mph": 12.5,
                            "wind_kph": 20.2,
                            "wind_degree": 145,
                            "wind_dir": "SE",
                            "pressure_mb": 1002.0,
                            "pressure_in": 29.58,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 79,
                            "cloud": 100,
                            "feelslike_c": 2.1,
                            "feelslike_f": 35.8,
                            "windchill_c": 2.1,
                            "windchill_f": 35.8,
                            "heatindex_c": 5.8,
                            "heatindex_f": 42.4,
                            "dewpoint_c": 2.4,
                            "dewpoint_f": 36.3,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 20.4,
                            "gust_kph": 32.8,
                            "uv": 2.0
                        },
                        {
                            "time_epoch": 1638874800,
                            "time": "2021-12-07 11:00",
                            "temp_c": 8.0,
                            "temp_f": 46.4,
                            "is_day": 1,
                            "condition": {
                                "text": "Overcast",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
                                "code": 1009
                            },
                            "wind_mph": 16.1,
                            "wind_kph": 25.9,
                            "wind_degree": 159,
                            "wind_dir": "SSE",
                            "pressure_mb": 999.0,
                            "pressure_in": 29.5,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 81,
                            "cloud": 100,
                            "feelslike_c": 4.3,
                            "feelslike_f": 39.7,
                            "windchill_c": 4.3,
                            "windchill_f": 39.7,
                            "heatindex_c": 8.0,
                            "heatindex_f": 46.4,
                            "dewpoint_c": 5.0,
                            "dewpoint_f": 41.0,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 23.7,
                            "gust_kph": 38.2,
                            "uv": 2.0
                        },
                        {
                            "time_epoch": 1638878400,
                            "time": "2021-12-07 12:00",
                            "temp_c": 7.6,
                            "temp_f": 45.7,
                            "is_day": 1,
                            "condition": {
                                "text": "Overcast",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
                                "code": 1009
                            },
                            "wind_mph": 17.9,
                            "wind_kph": 28.8,
                            "wind_degree": 158,
                            "wind_dir": "SSE",
                            "pressure_mb": 997.0,
                            "pressure_in": 29.43,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 84,
                            "cloud": 100,
                            "feelslike_c": 3.5,
                            "feelslike_f": 38.3,
                            "windchill_c": 3.5,
                            "windchill_f": 38.3,
                            "heatindex_c": 7.6,
                            "heatindex_f": 45.7,
                            "dewpoint_c": 5.0,
                            "dewpoint_f": 41.0,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 25.1,
                            "gust_kph": 40.3,
                            "uv": 2.0
                        },
                        {
                            "time_epoch": 1638882000,
                            "time": "2021-12-07 13:00",
                            "temp_c": 7.8,
                            "temp_f": 46.0,
                            "is_day": 1,
                            "condition": {
                                "text": "Light rain",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/296.png",
                                "code": 1183
                            },
                            "wind_mph": 17.9,
                            "wind_kph": 28.8,
                            "wind_degree": 158,
                            "wind_dir": "SSE",
                            "pressure_mb": 994.0,
                            "pressure_in": 29.34,
                            "precip_mm": 1.3,
                            "precip_in": 0.05,
                            "humidity": 88,
                            "cloud": 100,
                            "feelslike_c": 3.8,
                            "feelslike_f": 38.8,
                            "windchill_c": 3.8,
                            "windchill_f": 38.8,
                            "heatindex_c": 7.8,
                            "heatindex_f": 46.0,
                            "dewpoint_c": 5.9,
                            "dewpoint_f": 42.6,
                            "will_it_rain": 1,
                            "chance_of_rain": 94,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 9.0,
                            "vis_miles": 5.0,
                            "gust_mph": 24.8,
                            "gust_kph": 40.0,
                            "uv": 2.0
                        },
                        {
                            "time_epoch": 1638885600,
                            "time": "2021-12-07 14:00",
                            "temp_c": 8.2,
                            "temp_f": 46.8,
                            "is_day": 1,
                            "condition": {
                                "text": "Light drizzle",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/266.png",
                                "code": 1153
                            },
                            "wind_mph": 21.5,
                            "wind_kph": 34.6,
                            "wind_degree": 161,
                            "wind_dir": "SSE",
                            "pressure_mb": 990.0,
                            "pressure_in": 29.25,
                            "precip_mm": 0.7,
                            "precip_in": 0.03,
                            "humidity": 88,
                            "cloud": 100,
                            "feelslike_c": 3.9,
                            "feelslike_f": 39.0,
                            "windchill_c": 3.9,
                            "windchill_f": 39.0,
                            "heatindex_c": 8.2,
                            "heatindex_f": 46.8,
                            "dewpoint_c": 6.3,
                            "dewpoint_f": 43.3,
                            "will_it_rain": 1,
                            "chance_of_rain": 92,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 2.0,
                            "vis_miles": 1.0,
                            "gust_mph": 28.4,
                            "gust_kph": 45.7,
                            "uv": 2.0
                        },
                        {
                            "time_epoch": 1638889200,
                            "time": "2021-12-07 15:00",
                            "temp_c": 8.2,
                            "temp_f": 46.8,
                            "is_day": 1,
                            "condition": {
                                "text": "Moderate rain",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/302.png",
                                "code": 1189
                            },
                            "wind_mph": 24.4,
                            "wind_kph": 39.2,
                            "wind_degree": 158,
                            "wind_dir": "SSE",
                            "pressure_mb": 988.0,
                            "pressure_in": 29.17,
                            "precip_mm": 5.3,
                            "precip_in": 0.21,
                            "humidity": 87,
                            "cloud": 100,
                            "feelslike_c": 3.6,
                            "feelslike_f": 38.5,
                            "windchill_c": 3.6,
                            "windchill_f": 38.5,
                            "heatindex_c": 8.2,
                            "heatindex_f": 46.8,
                            "dewpoint_c": 6.2,
                            "dewpoint_f": 43.2,
                            "will_it_rain": 1,
                            "chance_of_rain": 93,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 7.0,
                            "vis_miles": 4.0,
                            "gust_mph": 30.6,
                            "gust_kph": 49.3,
                            "uv": 2.0
                        },
                        {
                            "time_epoch": 1638892800,
                            "time": "2021-12-07 16:00",
                            "temp_c": 8.5,
                            "temp_f": 47.3,
                            "is_day": 0,
                            "condition": {
                                "text": "Light drizzle",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/266.png",
                                "code": 1153
                            },
                            "wind_mph": 26.4,
                            "wind_kph": 42.5,
                            "wind_degree": 174,
                            "wind_dir": "S",
                            "pressure_mb": 987.0,
                            "pressure_in": 29.14,
                            "precip_mm": 0.3,
                            "precip_in": 0.01,
                            "humidity": 87,
                            "cloud": 100,
                            "feelslike_c": 3.8,
                            "feelslike_f": 38.8,
                            "windchill_c": 3.8,
                            "windchill_f": 38.8,
                            "heatindex_c": 8.5,
                            "heatindex_f": 47.3,
                            "dewpoint_c": 6.5,
                            "dewpoint_f": 43.7,
                            "will_it_rain": 1,
                            "chance_of_rain": 92,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 2.0,
                            "vis_miles": 1.0,
                            "gust_mph": 34.0,
                            "gust_kph": 54.7,
                            "uv": 1.0
                        },
                        {
                            "time_epoch": 1638896400,
                            "time": "2021-12-07 17:00",
                            "temp_c": 10.1,
                            "temp_f": 50.2,
                            "is_day": 0,
                            "condition": {
                                "text": "Patchy rain possible",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                                "code": 1063
                            },
                            "wind_mph": 13.4,
                            "wind_kph": 21.6,
                            "wind_degree": 234,
                            "wind_dir": "SW",
                            "pressure_mb": 989.0,
                            "pressure_in": 29.19,
                            "precip_mm": 1.3,
                            "precip_in": 0.05,
                            "humidity": 65,
                            "cloud": 76,
                            "feelslike_c": 7.3,
                            "feelslike_f": 45.1,
                            "windchill_c": 7.3,
                            "windchill_f": 45.1,
                            "heatindex_c": 10.1,
                            "heatindex_f": 50.2,
                            "dewpoint_c": 3.8,
                            "dewpoint_f": 38.8,
                            "will_it_rain": 1,
                            "chance_of_rain": 82,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 9.0,
                            "vis_miles": 5.0,
                            "gust_mph": 15.4,
                            "gust_kph": 24.8,
                            "uv": 1.0
                        },
                        {
                            "time_epoch": 1638900000,
                            "time": "2021-12-07 18:00",
                            "temp_c": 7.9,
                            "temp_f": 46.2,
                            "is_day": 0,
                            "condition": {
                                "text": "Partly cloudy",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                                "code": 1003
                            },
                            "wind_mph": 14.3,
                            "wind_kph": 23.0,
                            "wind_degree": 217,
                            "wind_dir": "SW",
                            "pressure_mb": 988.0,
                            "pressure_in": 29.18,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 71,
                            "cloud": 54,
                            "feelslike_c": 4.4,
                            "feelslike_f": 39.9,
                            "windchill_c": 4.4,
                            "windchill_f": 39.9,
                            "heatindex_c": 7.9,
                            "heatindex_f": 46.2,
                            "dewpoint_c": 3.1,
                            "dewpoint_f": 37.6,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 18.3,
                            "gust_kph": 29.5,
                            "uv": 1.0
                        },
                        {
                            "time_epoch": 1638903600,
                            "time": "2021-12-07 19:00",
                            "temp_c": 8.8,
                            "temp_f": 47.8,
                            "is_day": 0,
                            "condition": {
                                "text": "Clear",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                                "code": 1000
                            },
                            "wind_mph": 14.5,
                            "wind_kph": 23.4,
                            "wind_degree": 219,
                            "wind_dir": "SW",
                            "pressure_mb": 988.0,
                            "pressure_in": 29.18,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 69,
                            "cloud": 14,
                            "feelslike_c": 5.5,
                            "feelslike_f": 41.9,
                            "windchill_c": 5.5,
                            "windchill_f": 41.9,
                            "heatindex_c": 8.8,
                            "heatindex_f": 47.8,
                            "dewpoint_c": 3.5,
                            "dewpoint_f": 38.3,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 16.8,
                            "gust_kph": 27.0,
                            "uv": 1.0
                        },
                        {
                            "time_epoch": 1638907200,
                            "time": "2021-12-07 20:00",
                            "temp_c": 6.4,
                            "temp_f": 43.5,
                            "is_day": 0,
                            "condition": {
                                "text": "Partly cloudy",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                                "code": 1003
                            },
                            "wind_mph": 13.6,
                            "wind_kph": 22.0,
                            "wind_degree": 219,
                            "wind_dir": "SW",
                            "pressure_mb": 988.0,
                            "pressure_in": 29.18,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 71,
                            "cloud": 33,
                            "feelslike_c": 2.6,
                            "feelslike_f": 36.7,
                            "windchill_c": 2.6,
                            "windchill_f": 36.7,
                            "heatindex_c": 6.4,
                            "heatindex_f": 43.5,
                            "dewpoint_c": 1.6,
                            "dewpoint_f": 34.9,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 20.1,
                            "gust_kph": 32.4,
                            "uv": 1.0
                        },
                        {
                            "time_epoch": 1638910800,
                            "time": "2021-12-07 21:00",
                            "temp_c": 6.5,
                            "temp_f": 43.7,
                            "is_day": 0,
                            "condition": {
                                "text": "Partly cloudy",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                                "code": 1003
                            },
                            "wind_mph": 14.3,
                            "wind_kph": 23.0,
                            "wind_degree": 216,
                            "wind_dir": "SW",
                            "pressure_mb": 988.0,
                            "pressure_in": 29.18,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 70,
                            "cloud": 46,
                            "feelslike_c": 2.6,
                            "feelslike_f": 36.7,
                            "windchill_c": 2.6,
                            "windchill_f": 36.7,
                            "heatindex_c": 6.5,
                            "heatindex_f": 43.7,
                            "dewpoint_c": 1.5,
                            "dewpoint_f": 34.7,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 21.0,
                            "gust_kph": 33.8,
                            "uv": 1.0
                        },
                        {
                            "time_epoch": 1638914400,
                            "time": "2021-12-07 22:00",
                            "temp_c": 6.6,
                            "temp_f": 43.9,
                            "is_day": 0,
                            "condition": {
                                "text": "Partly cloudy",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                                "code": 1003
                            },
                            "wind_mph": 15.0,
                            "wind_kph": 24.1,
                            "wind_degree": 213,
                            "wind_dir": "SSW",
                            "pressure_mb": 988.0,
                            "pressure_in": 29.17,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 69,
                            "cloud": 46,
                            "feelslike_c": 2.7,
                            "feelslike_f": 36.9,
                            "windchill_c": 2.7,
                            "windchill_f": 36.9,
                            "heatindex_c": 6.6,
                            "heatindex_f": 43.9,
                            "dewpoint_c": 1.3,
                            "dewpoint_f": 34.3,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 21.9,
                            "gust_kph": 35.3,
                            "uv": 1.0
                        },
                        {
                            "time_epoch": 1638918000,
                            "time": "2021-12-07 23:00",
                            "temp_c": 6.8,
                            "temp_f": 44.2,
                            "is_day": 0,
                            "condition": {
                                "text": "Clear",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                                "code": 1000
                            },
                            "wind_mph": 16.3,
                            "wind_kph": 26.3,
                            "wind_degree": 216,
                            "wind_dir": "SW",
                            "pressure_mb": 988.0,
                            "pressure_in": 29.17,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 64,
                            "cloud": 9,
                            "feelslike_c": 2.7,
                            "feelslike_f": 36.9,
                            "windchill_c": 2.7,
                            "windchill_f": 36.9,
                            "heatindex_c": 6.8,
                            "heatindex_f": 44.2,
                            "dewpoint_c": 0.4,
                            "dewpoint_f": 32.7,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 23.7,
                            "gust_kph": 38.2,
                            "uv": 1.0
                        }
                    ]
                }
            ]
        }
    }
];